# Generated by Django 3.2.18 on 2023-03-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='menu_open',
            field=models.BooleanField(default=True),
        ),
    ]
