# Generated by Django 3.2.18 on 2023-03-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20230227_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='private',
        ),
        migrations.RemoveField(
            model_name='project',
            name='removed',
        ),
    ]
