# Generated by Django 3.2.18 on 2023-03-08 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
