# Generated by Django 3.2.18 on 2023-03-08 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_alter_project_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='contrib_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
