# Generated by Django 3.2.18 on 2023-03-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_contributors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated_on']},
        ),
    ]
