# Generated by Django 3.2.18 on 2023-03-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url_id',
        ),
    ]
