# Generated by Django 3.2.18 on 2023-03-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_project_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
