# Generated by Django 3.2.18 on 2023-03-28 21:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_task_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributors', '0002_auto_20230328_2154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('user', 'project')},
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='creator',
        ),
    ]
